/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedLiveMonitoringRouteImport } from './routes/_authenticated/live-monitoring'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authChangePasswordRouteImport } from './routes/(auth)/change-password'
import { Route as AuthenticatedVisitorsRouteRouteImport } from './routes/_authenticated/visitors/route'
import { Route as AuthenticatedVehiclesRouteRouteImport } from './routes/_authenticated/vehicles/route'
import { Route as AuthenticatedUsersRouteRouteImport } from './routes/_authenticated/users/route'
import { Route as AuthenticatedTrucksRouteRouteImport } from './routes/_authenticated/trucks/route'
import { Route as AuthenticatedReportsRouteRouteImport } from './routes/_authenticated/reports/route'
import { Route as AuthenticatedGatesRouteRouteImport } from './routes/_authenticated/gates/route'
import { Route as AuthenticatedContainerTuckRouteRouteImport } from './routes/_authenticated/container-tuck/route'
import { Route as AuthenticatedBlacklistRouteRouteImport } from './routes/_authenticated/blacklist/route'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedContainerTuckIndexRouteImport } from './routes/_authenticated/container-tuck/index'
import { Route as AuthenticatedTrucksExitRouteImport } from './routes/_authenticated/trucks/exit'
import { Route as AuthenticatedTrucksEntryRouteImport } from './routes/_authenticated/trucks/entry'
import { Route as AuthenticatedReportsVisitorsRouteImport } from './routes/_authenticated/reports/visitors'
import { Route as AuthenticatedReportsVehiclesRouteImport } from './routes/_authenticated/reports/vehicles'
import { Route as AuthenticatedReportsTrucksRouteImport } from './routes/_authenticated/reports/trucks'
import { Route as AuthenticatedExitRegistrationVisitorRouteImport } from './routes/_authenticated/exit-registration/visitor'
import { Route as AuthenticatedExitRegistrationVisitingVehicleRouteImport } from './routes/_authenticated/exit-registration/visiting-vehicle'
import { Route as AuthenticatedExitRegistrationContainerTruckRouteImport } from './routes/_authenticated/exit-registration/container-truck'
import { Route as AuthenticatedEntryRegistrationVisitorRouteImport } from './routes/_authenticated/entry-registration/visitor'
import { Route as AuthenticatedEntryRegistrationVisitingVehicleRouteImport } from './routes/_authenticated/entry-registration/visiting-vehicle'
import { Route as AuthenticatedEntryRegistrationContainerTruckRouteImport } from './routes/_authenticated/entry-registration/container-truck'
import { Route as AuthenticatedContainerTuckExsitRouteImport } from './routes/_authenticated/container-tuck/exsit'
import { Route as AuthenticatedContainerTuckEntryRouteImport } from './routes/_authenticated/container-tuck/entry'
import { Route as AuthenticatedExitRegistrationVisitorVisitorIdRouteImport } from './routes/_authenticated/exit-registration/visitor/$visitorId'
import { Route as AuthenticatedExitRegistrationVisitingVehicleVehicleIdRouteImport } from './routes/_authenticated/exit-registration/visiting-vehicle/$vehicleId'
import { Route as AuthenticatedExitRegistrationContainerTruckTruckIdRouteImport } from './routes/_authenticated/exit-registration/container-truck/$truckId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveMonitoringRoute =
  AuthenticatedLiveMonitoringRouteImport.update({
    id: '/live-monitoring',
    path: '/live-monitoring',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authChangePasswordRoute = authChangePasswordRouteImport.update({
  id: '/(auth)/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVisitorsRouteRoute =
  AuthenticatedVisitorsRouteRouteImport.update({
    id: '/visitors',
    path: '/visitors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVehiclesRouteRoute =
  AuthenticatedVehiclesRouteRouteImport.update({
    id: '/vehicles',
    path: '/vehicles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersRouteRoute = AuthenticatedUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrucksRouteRoute =
  AuthenticatedTrucksRouteRouteImport.update({
    id: '/trucks',
    path: '/trucks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRouteRoute =
  AuthenticatedReportsRouteRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGatesRouteRoute = AuthenticatedGatesRouteRouteImport.update({
  id: '/gates',
  path: '/gates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContainerTuckRouteRoute =
  AuthenticatedContainerTuckRouteRouteImport.update({
    id: '/container-tuck',
    path: '/container-tuck',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBlacklistRouteRoute =
  AuthenticatedBlacklistRouteRouteImport.update({
    id: '/blacklist',
    path: '/blacklist',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsRouteRoute,
  } as any)
const AuthenticatedContainerTuckIndexRoute =
  AuthenticatedContainerTuckIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedContainerTuckRouteRoute,
  } as any)
const AuthenticatedTrucksExitRoute = AuthenticatedTrucksExitRouteImport.update({
  id: '/exit',
  path: '/exit',
  getParentRoute: () => AuthenticatedTrucksRouteRoute,
} as any)
const AuthenticatedTrucksEntryRoute =
  AuthenticatedTrucksEntryRouteImport.update({
    id: '/entry',
    path: '/entry',
    getParentRoute: () => AuthenticatedTrucksRouteRoute,
  } as any)
const AuthenticatedReportsVisitorsRoute =
  AuthenticatedReportsVisitorsRouteImport.update({
    id: '/visitors',
    path: '/visitors',
    getParentRoute: () => AuthenticatedReportsRouteRoute,
  } as any)
const AuthenticatedReportsVehiclesRoute =
  AuthenticatedReportsVehiclesRouteImport.update({
    id: '/vehicles',
    path: '/vehicles',
    getParentRoute: () => AuthenticatedReportsRouteRoute,
  } as any)
const AuthenticatedReportsTrucksRoute =
  AuthenticatedReportsTrucksRouteImport.update({
    id: '/trucks',
    path: '/trucks',
    getParentRoute: () => AuthenticatedReportsRouteRoute,
  } as any)
const AuthenticatedExitRegistrationVisitorRoute =
  AuthenticatedExitRegistrationVisitorRouteImport.update({
    id: '/exit-registration/visitor',
    path: '/exit-registration/visitor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExitRegistrationVisitingVehicleRoute =
  AuthenticatedExitRegistrationVisitingVehicleRouteImport.update({
    id: '/exit-registration/visiting-vehicle',
    path: '/exit-registration/visiting-vehicle',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExitRegistrationContainerTruckRoute =
  AuthenticatedExitRegistrationContainerTruckRouteImport.update({
    id: '/exit-registration/container-truck',
    path: '/exit-registration/container-truck',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntryRegistrationVisitorRoute =
  AuthenticatedEntryRegistrationVisitorRouteImport.update({
    id: '/entry-registration/visitor',
    path: '/entry-registration/visitor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntryRegistrationVisitingVehicleRoute =
  AuthenticatedEntryRegistrationVisitingVehicleRouteImport.update({
    id: '/entry-registration/visiting-vehicle',
    path: '/entry-registration/visiting-vehicle',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntryRegistrationContainerTruckRoute =
  AuthenticatedEntryRegistrationContainerTruckRouteImport.update({
    id: '/entry-registration/container-truck',
    path: '/entry-registration/container-truck',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContainerTuckExsitRoute =
  AuthenticatedContainerTuckExsitRouteImport.update({
    id: '/exsit',
    path: '/exsit',
    getParentRoute: () => AuthenticatedContainerTuckRouteRoute,
  } as any)
const AuthenticatedContainerTuckEntryRoute =
  AuthenticatedContainerTuckEntryRouteImport.update({
    id: '/entry',
    path: '/entry',
    getParentRoute: () => AuthenticatedContainerTuckRouteRoute,
  } as any)
const AuthenticatedExitRegistrationVisitorVisitorIdRoute =
  AuthenticatedExitRegistrationVisitorVisitorIdRouteImport.update({
    id: '/$visitorId',
    path: '/$visitorId',
    getParentRoute: () => AuthenticatedExitRegistrationVisitorRoute,
  } as any)
const AuthenticatedExitRegistrationVisitingVehicleVehicleIdRoute =
  AuthenticatedExitRegistrationVisitingVehicleVehicleIdRouteImport.update({
    id: '/$vehicleId',
    path: '/$vehicleId',
    getParentRoute: () => AuthenticatedExitRegistrationVisitingVehicleRoute,
  } as any)
const AuthenticatedExitRegistrationContainerTruckTruckIdRoute =
  AuthenticatedExitRegistrationContainerTruckTruckIdRouteImport.update({
    id: '/$truckId',
    path: '/$truckId',
    getParentRoute: () => AuthenticatedExitRegistrationContainerTruckRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/blacklist': typeof AuthenticatedBlacklistRouteRoute
  '/container-tuck': typeof AuthenticatedContainerTuckRouteRouteWithChildren
  '/gates': typeof AuthenticatedGatesRouteRoute
  '/reports': typeof AuthenticatedReportsRouteRouteWithChildren
  '/trucks': typeof AuthenticatedTrucksRouteRouteWithChildren
  '/users': typeof AuthenticatedUsersRouteRoute
  '/vehicles': typeof AuthenticatedVehiclesRouteRoute
  '/visitors': typeof AuthenticatedVisitorsRouteRoute
  '/change-password': typeof authChangePasswordRoute
  '/sign-in': typeof authSignInRoute
  '/live-monitoring': typeof AuthenticatedLiveMonitoringRoute
  '/container-tuck/entry': typeof AuthenticatedContainerTuckEntryRoute
  '/container-tuck/exsit': typeof AuthenticatedContainerTuckExsitRoute
  '/entry-registration/container-truck': typeof AuthenticatedEntryRegistrationContainerTruckRoute
  '/entry-registration/visiting-vehicle': typeof AuthenticatedEntryRegistrationVisitingVehicleRoute
  '/entry-registration/visitor': typeof AuthenticatedEntryRegistrationVisitorRoute
  '/exit-registration/container-truck': typeof AuthenticatedExitRegistrationContainerTruckRouteWithChildren
  '/exit-registration/visiting-vehicle': typeof AuthenticatedExitRegistrationVisitingVehicleRouteWithChildren
  '/exit-registration/visitor': typeof AuthenticatedExitRegistrationVisitorRouteWithChildren
  '/reports/trucks': typeof AuthenticatedReportsTrucksRoute
  '/reports/vehicles': typeof AuthenticatedReportsVehiclesRoute
  '/reports/visitors': typeof AuthenticatedReportsVisitorsRoute
  '/trucks/entry': typeof AuthenticatedTrucksEntryRoute
  '/trucks/exit': typeof AuthenticatedTrucksExitRoute
  '/container-tuck/': typeof AuthenticatedContainerTuckIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/exit-registration/container-truck/$truckId': typeof AuthenticatedExitRegistrationContainerTruckTruckIdRoute
  '/exit-registration/visiting-vehicle/$vehicleId': typeof AuthenticatedExitRegistrationVisitingVehicleVehicleIdRoute
  '/exit-registration/visitor/$visitorId': typeof AuthenticatedExitRegistrationVisitorVisitorIdRoute
}
export interface FileRoutesByTo {
  '/blacklist': typeof AuthenticatedBlacklistRouteRoute
  '/gates': typeof AuthenticatedGatesRouteRoute
  '/trucks': typeof AuthenticatedTrucksRouteRouteWithChildren
  '/users': typeof AuthenticatedUsersRouteRoute
  '/vehicles': typeof AuthenticatedVehiclesRouteRoute
  '/visitors': typeof AuthenticatedVisitorsRouteRoute
  '/change-password': typeof authChangePasswordRoute
  '/sign-in': typeof authSignInRoute
  '/live-monitoring': typeof AuthenticatedLiveMonitoringRoute
  '/': typeof AuthenticatedIndexRoute
  '/container-tuck/entry': typeof AuthenticatedContainerTuckEntryRoute
  '/container-tuck/exsit': typeof AuthenticatedContainerTuckExsitRoute
  '/entry-registration/container-truck': typeof AuthenticatedEntryRegistrationContainerTruckRoute
  '/entry-registration/visiting-vehicle': typeof AuthenticatedEntryRegistrationVisitingVehicleRoute
  '/entry-registration/visitor': typeof AuthenticatedEntryRegistrationVisitorRoute
  '/exit-registration/container-truck': typeof AuthenticatedExitRegistrationContainerTruckRouteWithChildren
  '/exit-registration/visiting-vehicle': typeof AuthenticatedExitRegistrationVisitingVehicleRouteWithChildren
  '/exit-registration/visitor': typeof AuthenticatedExitRegistrationVisitorRouteWithChildren
  '/reports/trucks': typeof AuthenticatedReportsTrucksRoute
  '/reports/vehicles': typeof AuthenticatedReportsVehiclesRoute
  '/reports/visitors': typeof AuthenticatedReportsVisitorsRoute
  '/trucks/entry': typeof AuthenticatedTrucksEntryRoute
  '/trucks/exit': typeof AuthenticatedTrucksExitRoute
  '/container-tuck': typeof AuthenticatedContainerTuckIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/exit-registration/container-truck/$truckId': typeof AuthenticatedExitRegistrationContainerTruckTruckIdRoute
  '/exit-registration/visiting-vehicle/$vehicleId': typeof AuthenticatedExitRegistrationVisitingVehicleVehicleIdRoute
  '/exit-registration/visitor/$visitorId': typeof AuthenticatedExitRegistrationVisitorVisitorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/blacklist': typeof AuthenticatedBlacklistRouteRoute
  '/_authenticated/container-tuck': typeof AuthenticatedContainerTuckRouteRouteWithChildren
  '/_authenticated/gates': typeof AuthenticatedGatesRouteRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRouteRouteWithChildren
  '/_authenticated/trucks': typeof AuthenticatedTrucksRouteRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRouteRoute
  '/_authenticated/vehicles': typeof AuthenticatedVehiclesRouteRoute
  '/_authenticated/visitors': typeof AuthenticatedVisitorsRouteRoute
  '/(auth)/change-password': typeof authChangePasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/live-monitoring': typeof AuthenticatedLiveMonitoringRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/container-tuck/entry': typeof AuthenticatedContainerTuckEntryRoute
  '/_authenticated/container-tuck/exsit': typeof AuthenticatedContainerTuckExsitRoute
  '/_authenticated/entry-registration/container-truck': typeof AuthenticatedEntryRegistrationContainerTruckRoute
  '/_authenticated/entry-registration/visiting-vehicle': typeof AuthenticatedEntryRegistrationVisitingVehicleRoute
  '/_authenticated/entry-registration/visitor': typeof AuthenticatedEntryRegistrationVisitorRoute
  '/_authenticated/exit-registration/container-truck': typeof AuthenticatedExitRegistrationContainerTruckRouteWithChildren
  '/_authenticated/exit-registration/visiting-vehicle': typeof AuthenticatedExitRegistrationVisitingVehicleRouteWithChildren
  '/_authenticated/exit-registration/visitor': typeof AuthenticatedExitRegistrationVisitorRouteWithChildren
  '/_authenticated/reports/trucks': typeof AuthenticatedReportsTrucksRoute
  '/_authenticated/reports/vehicles': typeof AuthenticatedReportsVehiclesRoute
  '/_authenticated/reports/visitors': typeof AuthenticatedReportsVisitorsRoute
  '/_authenticated/trucks/entry': typeof AuthenticatedTrucksEntryRoute
  '/_authenticated/trucks/exit': typeof AuthenticatedTrucksExitRoute
  '/_authenticated/container-tuck/': typeof AuthenticatedContainerTuckIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/exit-registration/container-truck/$truckId': typeof AuthenticatedExitRegistrationContainerTruckTruckIdRoute
  '/_authenticated/exit-registration/visiting-vehicle/$vehicleId': typeof AuthenticatedExitRegistrationVisitingVehicleVehicleIdRoute
  '/_authenticated/exit-registration/visitor/$visitorId': typeof AuthenticatedExitRegistrationVisitorVisitorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blacklist'
    | '/container-tuck'
    | '/gates'
    | '/reports'
    | '/trucks'
    | '/users'
    | '/vehicles'
    | '/visitors'
    | '/change-password'
    | '/sign-in'
    | '/live-monitoring'
    | '/container-tuck/entry'
    | '/container-tuck/exsit'
    | '/entry-registration/container-truck'
    | '/entry-registration/visiting-vehicle'
    | '/entry-registration/visitor'
    | '/exit-registration/container-truck'
    | '/exit-registration/visiting-vehicle'
    | '/exit-registration/visitor'
    | '/reports/trucks'
    | '/reports/vehicles'
    | '/reports/visitors'
    | '/trucks/entry'
    | '/trucks/exit'
    | '/container-tuck/'
    | '/reports/'
    | '/exit-registration/container-truck/$truckId'
    | '/exit-registration/visiting-vehicle/$vehicleId'
    | '/exit-registration/visitor/$visitorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/blacklist'
    | '/gates'
    | '/trucks'
    | '/users'
    | '/vehicles'
    | '/visitors'
    | '/change-password'
    | '/sign-in'
    | '/live-monitoring'
    | '/'
    | '/container-tuck/entry'
    | '/container-tuck/exsit'
    | '/entry-registration/container-truck'
    | '/entry-registration/visiting-vehicle'
    | '/entry-registration/visitor'
    | '/exit-registration/container-truck'
    | '/exit-registration/visiting-vehicle'
    | '/exit-registration/visitor'
    | '/reports/trucks'
    | '/reports/vehicles'
    | '/reports/visitors'
    | '/trucks/entry'
    | '/trucks/exit'
    | '/container-tuck'
    | '/reports'
    | '/exit-registration/container-truck/$truckId'
    | '/exit-registration/visiting-vehicle/$vehicleId'
    | '/exit-registration/visitor/$visitorId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/blacklist'
    | '/_authenticated/container-tuck'
    | '/_authenticated/gates'
    | '/_authenticated/reports'
    | '/_authenticated/trucks'
    | '/_authenticated/users'
    | '/_authenticated/vehicles'
    | '/_authenticated/visitors'
    | '/(auth)/change-password'
    | '/(auth)/sign-in'
    | '/_authenticated/live-monitoring'
    | '/_authenticated/'
    | '/_authenticated/container-tuck/entry'
    | '/_authenticated/container-tuck/exsit'
    | '/_authenticated/entry-registration/container-truck'
    | '/_authenticated/entry-registration/visiting-vehicle'
    | '/_authenticated/entry-registration/visitor'
    | '/_authenticated/exit-registration/container-truck'
    | '/_authenticated/exit-registration/visiting-vehicle'
    | '/_authenticated/exit-registration/visitor'
    | '/_authenticated/reports/trucks'
    | '/_authenticated/reports/vehicles'
    | '/_authenticated/reports/visitors'
    | '/_authenticated/trucks/entry'
    | '/_authenticated/trucks/exit'
    | '/_authenticated/container-tuck/'
    | '/_authenticated/reports/'
    | '/_authenticated/exit-registration/container-truck/$truckId'
    | '/_authenticated/exit-registration/visiting-vehicle/$vehicleId'
    | '/_authenticated/exit-registration/visitor/$visitorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authChangePasswordRoute: typeof authChangePasswordRoute
  authSignInRoute: typeof authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live-monitoring': {
      id: '/_authenticated/live-monitoring'
      path: '/live-monitoring'
      fullPath: '/live-monitoring'
      preLoaderRoute: typeof AuthenticatedLiveMonitoringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/change-password': {
      id: '/(auth)/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof authChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/visitors': {
      id: '/_authenticated/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof AuthenticatedVisitorsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vehicles': {
      id: '/_authenticated/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AuthenticatedVehiclesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trucks': {
      id: '/_authenticated/trucks'
      path: '/trucks'
      fullPath: '/trucks'
      preLoaderRoute: typeof AuthenticatedTrucksRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gates': {
      id: '/_authenticated/gates'
      path: '/gates'
      fullPath: '/gates'
      preLoaderRoute: typeof AuthenticatedGatesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/container-tuck': {
      id: '/_authenticated/container-tuck'
      path: '/container-tuck'
      fullPath: '/container-tuck'
      preLoaderRoute: typeof AuthenticatedContainerTuckRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blacklist': {
      id: '/_authenticated/blacklist'
      path: '/blacklist'
      fullPath: '/blacklist'
      preLoaderRoute: typeof AuthenticatedBlacklistRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRouteRoute
    }
    '/_authenticated/container-tuck/': {
      id: '/_authenticated/container-tuck/'
      path: '/'
      fullPath: '/container-tuck/'
      preLoaderRoute: typeof AuthenticatedContainerTuckIndexRouteImport
      parentRoute: typeof AuthenticatedContainerTuckRouteRoute
    }
    '/_authenticated/trucks/exit': {
      id: '/_authenticated/trucks/exit'
      path: '/exit'
      fullPath: '/trucks/exit'
      preLoaderRoute: typeof AuthenticatedTrucksExitRouteImport
      parentRoute: typeof AuthenticatedTrucksRouteRoute
    }
    '/_authenticated/trucks/entry': {
      id: '/_authenticated/trucks/entry'
      path: '/entry'
      fullPath: '/trucks/entry'
      preLoaderRoute: typeof AuthenticatedTrucksEntryRouteImport
      parentRoute: typeof AuthenticatedTrucksRouteRoute
    }
    '/_authenticated/reports/visitors': {
      id: '/_authenticated/reports/visitors'
      path: '/visitors'
      fullPath: '/reports/visitors'
      preLoaderRoute: typeof AuthenticatedReportsVisitorsRouteImport
      parentRoute: typeof AuthenticatedReportsRouteRoute
    }
    '/_authenticated/reports/vehicles': {
      id: '/_authenticated/reports/vehicles'
      path: '/vehicles'
      fullPath: '/reports/vehicles'
      preLoaderRoute: typeof AuthenticatedReportsVehiclesRouteImport
      parentRoute: typeof AuthenticatedReportsRouteRoute
    }
    '/_authenticated/reports/trucks': {
      id: '/_authenticated/reports/trucks'
      path: '/trucks'
      fullPath: '/reports/trucks'
      preLoaderRoute: typeof AuthenticatedReportsTrucksRouteImport
      parentRoute: typeof AuthenticatedReportsRouteRoute
    }
    '/_authenticated/exit-registration/visitor': {
      id: '/_authenticated/exit-registration/visitor'
      path: '/exit-registration/visitor'
      fullPath: '/exit-registration/visitor'
      preLoaderRoute: typeof AuthenticatedExitRegistrationVisitorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exit-registration/visiting-vehicle': {
      id: '/_authenticated/exit-registration/visiting-vehicle'
      path: '/exit-registration/visiting-vehicle'
      fullPath: '/exit-registration/visiting-vehicle'
      preLoaderRoute: typeof AuthenticatedExitRegistrationVisitingVehicleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exit-registration/container-truck': {
      id: '/_authenticated/exit-registration/container-truck'
      path: '/exit-registration/container-truck'
      fullPath: '/exit-registration/container-truck'
      preLoaderRoute: typeof AuthenticatedExitRegistrationContainerTruckRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entry-registration/visitor': {
      id: '/_authenticated/entry-registration/visitor'
      path: '/entry-registration/visitor'
      fullPath: '/entry-registration/visitor'
      preLoaderRoute: typeof AuthenticatedEntryRegistrationVisitorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entry-registration/visiting-vehicle': {
      id: '/_authenticated/entry-registration/visiting-vehicle'
      path: '/entry-registration/visiting-vehicle'
      fullPath: '/entry-registration/visiting-vehicle'
      preLoaderRoute: typeof AuthenticatedEntryRegistrationVisitingVehicleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entry-registration/container-truck': {
      id: '/_authenticated/entry-registration/container-truck'
      path: '/entry-registration/container-truck'
      fullPath: '/entry-registration/container-truck'
      preLoaderRoute: typeof AuthenticatedEntryRegistrationContainerTruckRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/container-tuck/exsit': {
      id: '/_authenticated/container-tuck/exsit'
      path: '/exsit'
      fullPath: '/container-tuck/exsit'
      preLoaderRoute: typeof AuthenticatedContainerTuckExsitRouteImport
      parentRoute: typeof AuthenticatedContainerTuckRouteRoute
    }
    '/_authenticated/container-tuck/entry': {
      id: '/_authenticated/container-tuck/entry'
      path: '/entry'
      fullPath: '/container-tuck/entry'
      preLoaderRoute: typeof AuthenticatedContainerTuckEntryRouteImport
      parentRoute: typeof AuthenticatedContainerTuckRouteRoute
    }
    '/_authenticated/exit-registration/visitor/$visitorId': {
      id: '/_authenticated/exit-registration/visitor/$visitorId'
      path: '/$visitorId'
      fullPath: '/exit-registration/visitor/$visitorId'
      preLoaderRoute: typeof AuthenticatedExitRegistrationVisitorVisitorIdRouteImport
      parentRoute: typeof AuthenticatedExitRegistrationVisitorRoute
    }
    '/_authenticated/exit-registration/visiting-vehicle/$vehicleId': {
      id: '/_authenticated/exit-registration/visiting-vehicle/$vehicleId'
      path: '/$vehicleId'
      fullPath: '/exit-registration/visiting-vehicle/$vehicleId'
      preLoaderRoute: typeof AuthenticatedExitRegistrationVisitingVehicleVehicleIdRouteImport
      parentRoute: typeof AuthenticatedExitRegistrationVisitingVehicleRoute
    }
    '/_authenticated/exit-registration/container-truck/$truckId': {
      id: '/_authenticated/exit-registration/container-truck/$truckId'
      path: '/$truckId'
      fullPath: '/exit-registration/container-truck/$truckId'
      preLoaderRoute: typeof AuthenticatedExitRegistrationContainerTruckTruckIdRouteImport
      parentRoute: typeof AuthenticatedExitRegistrationContainerTruckRoute
    }
  }
}

interface AuthenticatedContainerTuckRouteRouteChildren {
  AuthenticatedContainerTuckEntryRoute: typeof AuthenticatedContainerTuckEntryRoute
  AuthenticatedContainerTuckExsitRoute: typeof AuthenticatedContainerTuckExsitRoute
  AuthenticatedContainerTuckIndexRoute: typeof AuthenticatedContainerTuckIndexRoute
}

const AuthenticatedContainerTuckRouteRouteChildren: AuthenticatedContainerTuckRouteRouteChildren =
  {
    AuthenticatedContainerTuckEntryRoute: AuthenticatedContainerTuckEntryRoute,
    AuthenticatedContainerTuckExsitRoute: AuthenticatedContainerTuckExsitRoute,
    AuthenticatedContainerTuckIndexRoute: AuthenticatedContainerTuckIndexRoute,
  }

const AuthenticatedContainerTuckRouteRouteWithChildren =
  AuthenticatedContainerTuckRouteRoute._addFileChildren(
    AuthenticatedContainerTuckRouteRouteChildren,
  )

interface AuthenticatedReportsRouteRouteChildren {
  AuthenticatedReportsTrucksRoute: typeof AuthenticatedReportsTrucksRoute
  AuthenticatedReportsVehiclesRoute: typeof AuthenticatedReportsVehiclesRoute
  AuthenticatedReportsVisitorsRoute: typeof AuthenticatedReportsVisitorsRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
}

const AuthenticatedReportsRouteRouteChildren: AuthenticatedReportsRouteRouteChildren =
  {
    AuthenticatedReportsTrucksRoute: AuthenticatedReportsTrucksRoute,
    AuthenticatedReportsVehiclesRoute: AuthenticatedReportsVehiclesRoute,
    AuthenticatedReportsVisitorsRoute: AuthenticatedReportsVisitorsRoute,
    AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  }

const AuthenticatedReportsRouteRouteWithChildren =
  AuthenticatedReportsRouteRoute._addFileChildren(
    AuthenticatedReportsRouteRouteChildren,
  )

interface AuthenticatedTrucksRouteRouteChildren {
  AuthenticatedTrucksEntryRoute: typeof AuthenticatedTrucksEntryRoute
  AuthenticatedTrucksExitRoute: typeof AuthenticatedTrucksExitRoute
}

const AuthenticatedTrucksRouteRouteChildren: AuthenticatedTrucksRouteRouteChildren =
  {
    AuthenticatedTrucksEntryRoute: AuthenticatedTrucksEntryRoute,
    AuthenticatedTrucksExitRoute: AuthenticatedTrucksExitRoute,
  }

const AuthenticatedTrucksRouteRouteWithChildren =
  AuthenticatedTrucksRouteRoute._addFileChildren(
    AuthenticatedTrucksRouteRouteChildren,
  )

interface AuthenticatedExitRegistrationContainerTruckRouteChildren {
  AuthenticatedExitRegistrationContainerTruckTruckIdRoute: typeof AuthenticatedExitRegistrationContainerTruckTruckIdRoute
}

const AuthenticatedExitRegistrationContainerTruckRouteChildren: AuthenticatedExitRegistrationContainerTruckRouteChildren =
  {
    AuthenticatedExitRegistrationContainerTruckTruckIdRoute:
      AuthenticatedExitRegistrationContainerTruckTruckIdRoute,
  }

const AuthenticatedExitRegistrationContainerTruckRouteWithChildren =
  AuthenticatedExitRegistrationContainerTruckRoute._addFileChildren(
    AuthenticatedExitRegistrationContainerTruckRouteChildren,
  )

interface AuthenticatedExitRegistrationVisitingVehicleRouteChildren {
  AuthenticatedExitRegistrationVisitingVehicleVehicleIdRoute: typeof AuthenticatedExitRegistrationVisitingVehicleVehicleIdRoute
}

const AuthenticatedExitRegistrationVisitingVehicleRouteChildren: AuthenticatedExitRegistrationVisitingVehicleRouteChildren =
  {
    AuthenticatedExitRegistrationVisitingVehicleVehicleIdRoute:
      AuthenticatedExitRegistrationVisitingVehicleVehicleIdRoute,
  }

const AuthenticatedExitRegistrationVisitingVehicleRouteWithChildren =
  AuthenticatedExitRegistrationVisitingVehicleRoute._addFileChildren(
    AuthenticatedExitRegistrationVisitingVehicleRouteChildren,
  )

interface AuthenticatedExitRegistrationVisitorRouteChildren {
  AuthenticatedExitRegistrationVisitorVisitorIdRoute: typeof AuthenticatedExitRegistrationVisitorVisitorIdRoute
}

const AuthenticatedExitRegistrationVisitorRouteChildren: AuthenticatedExitRegistrationVisitorRouteChildren =
  {
    AuthenticatedExitRegistrationVisitorVisitorIdRoute:
      AuthenticatedExitRegistrationVisitorVisitorIdRoute,
  }

const AuthenticatedExitRegistrationVisitorRouteWithChildren =
  AuthenticatedExitRegistrationVisitorRoute._addFileChildren(
    AuthenticatedExitRegistrationVisitorRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBlacklistRouteRoute: typeof AuthenticatedBlacklistRouteRoute
  AuthenticatedContainerTuckRouteRoute: typeof AuthenticatedContainerTuckRouteRouteWithChildren
  AuthenticatedGatesRouteRoute: typeof AuthenticatedGatesRouteRoute
  AuthenticatedReportsRouteRoute: typeof AuthenticatedReportsRouteRouteWithChildren
  AuthenticatedTrucksRouteRoute: typeof AuthenticatedTrucksRouteRouteWithChildren
  AuthenticatedUsersRouteRoute: typeof AuthenticatedUsersRouteRoute
  AuthenticatedVehiclesRouteRoute: typeof AuthenticatedVehiclesRouteRoute
  AuthenticatedVisitorsRouteRoute: typeof AuthenticatedVisitorsRouteRoute
  AuthenticatedLiveMonitoringRoute: typeof AuthenticatedLiveMonitoringRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedEntryRegistrationContainerTruckRoute: typeof AuthenticatedEntryRegistrationContainerTruckRoute
  AuthenticatedEntryRegistrationVisitingVehicleRoute: typeof AuthenticatedEntryRegistrationVisitingVehicleRoute
  AuthenticatedEntryRegistrationVisitorRoute: typeof AuthenticatedEntryRegistrationVisitorRoute
  AuthenticatedExitRegistrationContainerTruckRoute: typeof AuthenticatedExitRegistrationContainerTruckRouteWithChildren
  AuthenticatedExitRegistrationVisitingVehicleRoute: typeof AuthenticatedExitRegistrationVisitingVehicleRouteWithChildren
  AuthenticatedExitRegistrationVisitorRoute: typeof AuthenticatedExitRegistrationVisitorRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBlacklistRouteRoute: AuthenticatedBlacklistRouteRoute,
  AuthenticatedContainerTuckRouteRoute:
    AuthenticatedContainerTuckRouteRouteWithChildren,
  AuthenticatedGatesRouteRoute: AuthenticatedGatesRouteRoute,
  AuthenticatedReportsRouteRoute: AuthenticatedReportsRouteRouteWithChildren,
  AuthenticatedTrucksRouteRoute: AuthenticatedTrucksRouteRouteWithChildren,
  AuthenticatedUsersRouteRoute: AuthenticatedUsersRouteRoute,
  AuthenticatedVehiclesRouteRoute: AuthenticatedVehiclesRouteRoute,
  AuthenticatedVisitorsRouteRoute: AuthenticatedVisitorsRouteRoute,
  AuthenticatedLiveMonitoringRoute: AuthenticatedLiveMonitoringRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedEntryRegistrationContainerTruckRoute:
    AuthenticatedEntryRegistrationContainerTruckRoute,
  AuthenticatedEntryRegistrationVisitingVehicleRoute:
    AuthenticatedEntryRegistrationVisitingVehicleRoute,
  AuthenticatedEntryRegistrationVisitorRoute:
    AuthenticatedEntryRegistrationVisitorRoute,
  AuthenticatedExitRegistrationContainerTruckRoute:
    AuthenticatedExitRegistrationContainerTruckRouteWithChildren,
  AuthenticatedExitRegistrationVisitingVehicleRoute:
    AuthenticatedExitRegistrationVisitingVehicleRouteWithChildren,
  AuthenticatedExitRegistrationVisitorRoute:
    AuthenticatedExitRegistrationVisitorRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authChangePasswordRoute: authChangePasswordRoute,
  authSignInRoute: authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
